---
# tasks file for nginx-role
- name: Setting host facts
  ansible.builtin.set_fact:
    add_cfg: "{{ ngx_repl_config }}"
- block:
  - name: add repo nginx in RedHat
    ansible.builtin.copy:
      dest: /etc/yum.repos.d/nginx.repo
      mode: '0755'
      content: |
        [nginx]
        name=nginx repo
        baseurl=https://nginx.org/packages/centos/$releasever/$basearch/
        gpgcheck=0
        enabled=1
  - name: check repo CentOS
    ansible.builtin.shell: grep "#baseurl=http://mirror.centos.org" /etc/yum.repos.d/CentOS-* | wc -m
    changed_when: false
    register: checkRepoChange
    when: ansible_distribution_major_version == "8"
  - name: Replace CentOS repo
    ansible.builtin.shell: |
      /usr/bin/sed -i 's/mirrorlist=http/#mirrorlist=http/g' /etc/yum.repos.d/CentOS-* 
      /usr/bin/sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
    when: ansible_distribution_major_version == "8" and checkRepoChange.stdout != "0"
  - name: install nginx
    ansible.builtin.yum:
      name: nginx
      state: latest
      update_cache: yes
    when: not ansible_check_mode
  become: true
  when: ansible_os_family == "RedHat"
- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: yes
  when: not ansible_check_mode and ansible_os_family == "Debian"
  become: true
- name: Configure nginx from template
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_dir }}/conf.d/default.conf"
  when: add_cfg == "true"
  become: true
  notify: restarted nginx service
- name: Flush handlers
  meta: flush_handlers
